set(scratch_directory ${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY})
message(STATUS "Checking for restrict keyword")
foreach(KEYWORD "restrict" "__restrict__" "__restrict")
    if(NOT DEFINED C_restrict)
        TRY_COMPILE(C_HAS_${KEYWORD} "${scratch_directory}" "${CMAKE_SOURCE_DIR}/cmake/test_restrict.c"
            COMPILE_DEFINITIONS "-Drestrict=${KEYWORD}")
        if(C_HAS_${KEYWORD})
            set(C_restrict TRUE)
            ADD_DEFINITIONS("-Drestrict=${KEYWORD}")
        ENDIF(C_HAS_${KEYWORD})
    ENDIF(NOT DEFINED C_restrict)
ENDFOREACH(KEYWORD)
IF(NOT DEFINED C_restrict)
    ADD_DEFINITIONS("-Drestrict=")
ENDIF(NOT DEFINED C_restrict)
